### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by tab58** [scijs/ndarray-blas-level1#10]
I'm raising this issue because of my love for semicolons (can we really rely on semicolon insertion?). I'm fine if that's the style, but I think there ought to be a style guide for future collaboration.

Feel free to push back on this.

**Comment by rreusser** [comment]
I appreciate the feedback! And I agree about the style guide. There's way too much inconsistency across scijs. As for ASI, I don't really have a strong preference on the matter, but here's a complete rundown of why I've gravitated toward no semicolons:
1. A desired to avoid [bikeshedding](https://www.freebsd.org/doc/en_US.ISO8859-1/books/faq/misc.html#idp60690640). In my opinion (feel free to push back on this :smile:) it's probably more important to define _a_ style guide than to attempt to determine _the correct_ style guide—though I've failed to do this so far. Regarding standardjs, I find the ["Not configurable" stance](https://github.com/feross/standard#can-you-make-rule-x-configurable) rather compelling. It sounds like you may prefer [semistandard js](https://github.com/Flet/semistandard) :smile:
2. Tested code is subject to the interpreter which performs ASI.
3. Minified code will get semicolons anyway.
4. To the best of my knowledge, [ASI is safe](http://inimino.org/~inimino/blog/javascript_semicolons). Standard js for one enforces the conventions that would cause problems—like [starting a line with [ or (](https://github.com/feross/standard#rules).
5. Using semicolons doesn't mean you don't still need to understand ASI. Note that this function always returns `undefined` due to ASI, despite using semicolons:

``` javascript
var computeThreePlusFive = function () {
  return
    (3 + 5);
};
```

So that's why I've kinda gone the direction I have, but if a style guide changed and the code could be linted with little or no configuration, I'd be perfectly happy.

I'd love to sweep through all of scijs and apply these conventions. Frankly, it's been a shortage of time and collaborators that have prevented this so far, although I'd definitely believe it if you told me the lack of clear styles and guidelines has kept collaborators away in the first place. :disappointed:

**Comment by tab58** [comment]
+1 for avoiding bikeshedding. I really don't care what the style is as long as there's some guide to follow. Personally, I like the Google JS style guide and what I've seen of semistandard.js. It seems there hasn't been a lot of need for a specific style as there haven't been more than a few contributors to a project, but I think maybe that's a talking point with the rest of the scijs team.

About ASI, I can see your point. However, I respectfully disagree with relying on it. In my opinion, ASI has a similar function to a style guide. Ideally, they're supposed to keep you from doing stupid things that will create hard-to-find bugs, like your example of the `computeThreePlusFive` function. I've seen many articles saying it's okay to leave out the semicolons, but I don't quite get the logic of heavily relying on the ASI to put in what people have intentionally left out. Besides, it's a C-like syntax, so it's weird without the semicolons :-)

I would be fine with helping convert code over to a specific style as I try to contribute to the specific projects. While I don't think the style has necessarily driven away contributors, I think having well-defined parameters will help contributors (like me) in the future.

**Comment by rreusser** [comment]
Sounds good to me. Do you think semi standard is a good choice then? Except for the contentious issue of semicolons, I think all the other stuff is lovely and zero-config is certainly nice.

How about this. I'll make a guidelines repo. We can hash out a few issues there and then apply them where appropriate in a broad sweep. There are a few other points that I think would help consistency and maintenance. There's also a scijs-generator module around here somewhere. I don't like generators in general, but I think this is a place where it could be rather helpful in atartingg things out with some baseline consistency.

(Finally—regarding my wording as I look back—I certainly don't mean to claim any sort of ownership over scijs; in the world of [Starters and Maintainers](http://jlongster.com/Starters-and-Maintainers), I'd consider myself a maintainer at best! Need to get back into it and pull these things together though.)

**Comment by tab58** [comment]
> I'll make a guidelines repo. We can hash out a few issues there and then apply them where appropriate in a broad sweep. There are a few other points that I think would help consistency and maintenance.

Yeah, let's move this discussion there.

**Comment by rreusser** [comment]
See: https://github.com/scijs/contributing
