### ISSUE TITLE
Use cwise as a transform

### ISSUE THREAD

**Issue by mikolalysenko** [scijs/ndarray-blas-level1#2]
This is awesome!  One suggestion though is that you should consider adding cwise as a browserify transform.  That way when you ship out bundles it will generate less code overall, saving the esprima dependency.

To do this, all you have to do is add the following field to your package.json:

```
  "browserify": {
    "transform": [
      "cwise"
    ]
  }
```

**Comment by mikolalysenko** [comment]
(also this needs to be done to a lot of older modules, which also need to get their semver bumped up to 1.0.0)

**Comment by rreusser** [comment]
Cool… that was easy… I think… I need to test browserify for myself once more to clarify for myself all the details. Side note on browserify: I didn't like using node's `assert` module since it brought in a bunch of formatting and coloring stuff. Feels like there should be an equivalent and consistent one-liner that would be better.
